### ISSUE TITLE
Support for NextJs?

### ISSUE THREAD

**Issue by peter-novak-m** [TurtIeSocks/react-leaflet-geoman#6]
Hi TurtleSocks!

This looks like a nice package, but is it supported yet in NextJs? I got the following error:

> - error ./node_modules/@geoman-io/leaflet-geoman-free/dist/leaflet-geoman.css
> Global CSS cannot be imported from within node_modules.
> Read more: https://nextjs.org/docs/messages/css-npm
> Location: node_modules/react-leaflet-geoman-v2/dist/GeomanControls.js
> 
> Import trace for requested module:
> ./node_modules/@geoman-io/leaflet-geoman-free/dist/leaflet-geoman.css
> ./node_modules/react-leaflet-geoman-v2/dist/GeomanControls.js
> ./node_modules/react-leaflet-geoman-v2/dist/index.js
> ./src/modules/project/components/MapArea/Map.tsx
> ./src/modules/project/components/MapArea/index.tsx
> ./src/modules/project/view/ProjectView.tsx

When trying out this code:

```
import "leaflet/dist/leaflet.css";
import { MapContainer, TileLayer, FeatureGroup } from "react-leaflet";
import { GeomanControls } from "react-leaflet-geoman-v2";

export default function Map() {
  return (
    <MapContainer
      center={{ lat: 0.67, lng: 114.0 }}
      zoom={7}
      style={{ height: "100vh" }}
    >
      <TileLayer
        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
        attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
      />
      <Drawing />
    </MapContainer>
  );
}

function Drawing() {
  const handleChange = () => {
    console.log("Event fired!");
  };
  return (
    <FeatureGroup>
      <GeomanControls
        options={{
          position: "topleft",
          drawText: false,
        }}
        globalOptions={{
          continueDrawing: true,
          editable: false,
        }}
        onCreate={handleChange}
        onChange={(e) => console.log("onChange", e)}
      />
    </FeatureGroup>
  );
}
```

Have been looking around for exactly this kind of wrapper, so would be awesome if it would work in NextJs as well!

**Comment by TurtIeSocks** [comment]
Fixed in latest. This module no longer imports the CSS for Geoman, you'll need to do that yourself but I tested and verified that it works with NextJS.
