### ISSUE TITLE
react-leaflet peer dependency

### ISSUE THREAD

**Issue by ongjiinjoo** [TurtIeSocks/react-leaflet-geoman#9]
Possible to loosen peer dependencies on react-leaflet to support all 4.x.x series? It's currently [4.2.1](https://github.com/PaulLeCam/react-leaflet/releases/) 

```
npm ERR! Conflicting peer dependency: react-leaflet@4.2.1
npm ERR! node_modules/react-leaflet
npm ERR!   peer react-leaflet@"^4.0.2" from react-leaflet-geoman-v2@1.0.0
npm ERR!   node_modules/react-leaflet-geoman-v2
npm ERR!     react-leaflet-geoman-v2@"^1.0.0" from the root project
```

**Comment by TurtIeSocks** [comment]
I believe this should have been resolved in in #10 / v1.0.1. New version should be live on NPM shortly. Thanks for the heads up!
